---
infinispan_url: "site2-datagrid1{{ domain_name }}"
jdg_jgroups_relay_site: site2
jdg_jdbc_url: jdbc:mariadb:sequential://site2-database1,site1-database1,site1-database2:3306/keycloak
keycloak_jdbc_url: jdbc:mariadb:sequential://site2-database1,site1-database1,site1-database2:3306/keycloak